import type { Metadata } from "next";
import "./globals.css";
import MainLayout from "@/components/mianLayout";
import { CartContextProvider } from "@/context/cartContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body>
        <CartContextProvider>
          <MainLayout>{children}</MainLayout>
        </CartContextProvider>
      </body>
    </html>
  );
}
